### ISSUE TITLE
Management methods

### ISSUE THREAD

**Issue by behrad** [moscajs/aedes#139]
Implement more instance functions
- `aedes.instances()`: returns current running brokers list 
- `aedes.isConnected(clientId)`: returns if a clientId is currently connected to any aedes instance or not (all aedes instance can currently keep track of connected clientIds)

**Comment by GavinDmello** [comment]
> aedes.isConnected(clientId) 
How are you planning on doing this ?

**Comment by nguyenthenguyen** [comment]
Should we check list of client instead of one client ?. Ex: `aedes.clientStatus(ids)`, `ids` is a list of client ID

**Comment by cordovapolymer** [comment]
currently we are managing the list of connected clients in server app and on client side, by publishing a special message on user connect, and using a will message to track disconnections.

**Comment by mcollina** [comment]
So, `aedes.isConnected(id)` will not work, because a single server can only know about all the clients that have connected _while it was running_. Another option is to make that async, and fire a broadcast to all the servers if it didn't see the client. It's quite an expensive method in the worst case scenario.

I think `aedes.isConnected(id)` can be  implemented in another module.

**Comment by nguyenthenguyen** [comment]
@cordovapolymer When we using will message for connect status, this [issues](https://github.com/mcollina/aedes/pull/105#issuecomment-294077886) will make wrong logic

**Comment by mcollina** [comment]
That's not clear :/.

**Comment by nguyenthenguyen** [comment]
@mcollina @cordovapolymer  When we have 2 aedes instance: aedes A and aedes B (A <=> B use mqemiter), client C.
Step 1. C connect to A use will topic mean `c offline`. C have status online
Step 2. A crash => stop
Step 3. C disconnect to A because A crash
Step 4. C auto reconnect to B. C status is online
Step 5. B run `clearWillInterval` publish will topic `c offline`. But C current online

**Comment by GavinDmello** [comment]
@nguyenthenguyen Are you publishing to the same will topic when the client connects ?
If yes, Have you tried reducing the heartbeatInterval ?

**Comment by nguyenthenguyen** [comment]
@GavinDmello You can use [this sample](https://github.com/mcollina/aedes/pull/98#issuecomment-291090278) for one aedes instance (will fail logic too) and [my comments](https://github.com/mcollina/aedes/pull/105#issuecomment-294077886)

**Comment by GavinDmello** [comment]
@nguyenthenguyen  Have you tried publishing a retained message on connect to client1/status ?

**Comment by nguyenthenguyen** [comment]
@GavinDmello Yes! This happen even if I publish retained message on connect to client1/status. Because after restart, `aedes` have new id and old retain of client status topic belongs to old id, this will run [`checkAndPublish`](https://github.com/mcollina/aedes/blob/master/aedes.js#L93)

**Step to reducing this:**
Step 1: Start server.js
Step 2: start client1.js
Step 3: start client2.js
Step 4: stop server.js
Step 5: start server.js
Step 6: See client2.js log

**Code:**
_server.js_
```
var redisPersistence = require('aedes-persistence-redis');
var aedes = require('aedes')({
    persistence: redisPersistence({
	    "port": 6379,          
      "host": "127.0.0.1",
      "family": 4,
      "password": "",
      "db": 1
      }),
    heartbeatInterval: 1000 // more fast to test
});

var mqttServer = require('net').createServer(aedes.handle);

var mqttPort = 1883
mqttServer.listen(mqttPort,"0.0.0.0", function () {
  console.log('mqtt server listening on port', mqttPort)
});
```
_Client1.js_
```
var mqtt = require('mqtt')
var client  = mqtt.connect('mqtt://localhost:1883',{
    will:{
        topic:"client1/status",
        payload: "client1 offline",
        qos: 0,
        retain: true
    }
})

client.on('connect', function () {
    console.log("Client 1 connected")
    client.publish('client1/status', 'client1 online', {
        retain: true
    })
})

client.on('message', function (topic, message) {
  console.log(message.toString())
})

```

_client2.js_
```
var mqtt = require('mqtt')
var client  = mqtt.connect('mqtt://localhost:1883',{
    will:{
        topic:"client2/status",
        payload: "client2 offline",
        qos: 0,
        retain: true
    }
})

client.on('connect', function () {
    console.log("Client 2 connected")
    client.subscribe('client1/status')
})

client.on('message', function (topic, message) {
  console.log(message.toString())
})
```

**Comment by GavinDmello** [comment]
@nguyenthenguyen I tried it out . So this is when the client quickly reconnects within the heartbeat interval to another node and then the will is published. 
Have you played around with the heartbeatInterval ?  It did not reoccur when I reduced it to 100 ms.

**Comment by nguyenthenguyen** [comment]
@GavinDmello Not yet! The default `heartbeatInterval` is 60 seconds and after [4*60s ](https://github.com/mcollina/aedes/blob/master/aedes.js#L87) it will happend. How about performance If we change `heartbeatInterval` to 100ms ? This is a bug?

**Comment by mcollina** [comment]
Something like 1s should be better. However, I do not think that's the best approach. We should change that logic so that we do not send the will if the client reconnects in the meantime to another server.

**Comment by GavinDmello** [comment]
According to the MQTT docs
```
The Server SHOULD publish Will Messages promptly. In the case of a Server shutdown or failure the server MAY defer publication of Will Messages until a subsequent restart. If this happens there might be a delay between the time the server experienced failure and a Will Message being published.
```
It's a bit ambiguous for another broker to send wills for a dead broker.

**Comment by mcollina** [comment]
One approach could be to check when a client connects if there are will messages to be sent with that clientId.

All aedes broker act in unison, so they should appear like "one".

**Comment by robertsLando** [comment]
@mcollina 

> We should change that logic so that we do not send the will if the client reconnects in the meantime to another server

This has been fixed in recent commits. Can I close this one?
